# Generated by Django 2.2 on 2019-04-08 18:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('last_fetch', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=100)),
                ('url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RSSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper_rss.RSSTypes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
