# Generated by Django 2.2 on 2019-04-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_rss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsstypes',
            name='last_fetch',
            field=models.DateTimeField(null=True),
        ),
    ]
